project:
  type: website
  output-dir: _site

format:
  html:
    df-print: paged
    theme:
      light: ./capsules/styles_light.scss
      dark: ./capsules/styles_dark.scss
    toc: true
    lang: fr

website:
  page-navigation: true
  repo-url: https://github.com/PMassicotte/capsules_r_ulaval2
  repo-actions: [issue]
  title: "Capsules R ULAVAL"
  navbar:
    right:
      - href: index.qmd
        text: Accueil
      - text: "Capsules"
        file: capsules/index.qmd
      - icon: github
        href: "https://github.com/PMassicotte/capsules_r_ulaval2"
        aria-label: "GitHub"

  sidebar:
    logo: "https://natalierousseau.ca/wp-content/uploads/2018/03/logo-ulaval-reseaux-sociaux.jpg"
    pinned: true
    align: center
    # tools:
    #   # https://icons.getbootstrap.com/
    #   - icon: "browser-firefox"
    #     href: https://www.ulaval.ca/
    #     text: "Site de l'Université Laval"
    #   - icon: "globe"
    #     href: https://www.ulaval.ca/
    #   - icon: "envelope-at"
    #     href: https://www.ulaval.ca/
    #     text: "Site de l'Université Laval"
    style: "docked"
    search: true
    contents:
      - section: "À propos"
        contents:
          - capsules/index.qmd
      - section: "Capsules"
        contents:
          - text: "Capsule 1"
            file: capsules/01-capsule.qmd
          - text: "Capsule 2"
            file: capsules/02-capsule.qmd
          - text: "Capsule 3"
            file: capsules/03-capsule.qmd
          - text: "Capsule 4"
            file: capsules/04-capsule.qmd
          - text: "Capsule 5"
            file: capsules/05-capsule.qmd
          - text: "Capsule 6"
            file: capsules/06-capsule.qmd
          - text: "Capsule 7"
            file: capsules/07-capsule.qmd
          - text: "Capsule 8"
            file: capsules/08-capsule.qmd
          - text: "Capsule 9"
            file: capsules/09-capsule.qmd
          - text: "Capsule 10"
            file: capsules/10-capsule.qmd
          - text: "Capsule 11"
            file: capsules/11-capsule.qmd

  page-footer:
    right: "Ce site web a été réalisé à l'aide de [Quarto](https://quarto.org/) et de [webr](https://docs.r-wasm.org/webr/latest/)."
    left: "&copy; CC-By xxx, 2024. Capsules réalisées par N. Aubin-Horth, F. Maps, P. Massicotte et Esther Kros."
